CREATE TABLE dbo.SKU
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Code AS ('s' + CAST(ID AS VARCHAR(50))),
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE dbo.Family
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	SurName VARCHAR(255) NOT NULL,
	BudgetValue DECIMAL (18, 2) NOT NULL
);

CREATE TABLE dbo.Basket
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	ID_SKU INT FOREIGN KEY REFERENCES dbo.SKU(ID),
	ID_Family INT FOREIGN KEY REFERENCES dbo.Family(ID),
	Quantity INT CHECK (Quantity >= 0) NOT NULL,
	Value DECIMAL (18, 2) CHECK (Value >= 0) NOT NULL,
	PurchaseDate DATE DEFAULT GETDATE(),
	DiscountValue DECIMAL (18, 2)
);